language: cpp

dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
 - clang
 - gcc

before_install:
  - |
    echo "Updating dependencies..."
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew update); fi
    if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CXX" == "clang++" ]; then (brew outdated llvm) || (brew unlink llvm && brew upgrade llvm); fi
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew outdated cmake) || (brew unlink cmake && brew upgrade cmake); fi
    echo ${PATH}
    git --version
    cmake --version
    ${CXX} --version
    ${CXX} -v

before_script:
  - echo "Compiling with $CXX on $TRAVIS_OS_NAME"
  - $CC --version
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DBUILD_LZMA=1 ..

script: make
